title: miim
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  miim is yet another IDE, inspired by the great emacs and vim.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
sass:
  style: compressed
